Multilingual/content
IDinsight/aaq-core pull request #137
Opened 2024-03-22 16:19 UTC by lickem22

Reviewer: @sidravi1 

Estimate: 1h30mins

---

## Ticket

Fixes: Part of [AAQ-399](https://idinsight.atlassian.net/browse/AAQ-399)

## Description, Motivation and Context

### Goal
The goal of this PR is to update the frontend and the backend to be able to add new contents the multilingual way. 
### Changes
The following changes have been made on the backend:
- Updated the database to support multilingual contents. I added in the migration file a query to create a first default language. Since adding a frontend for language management is out of scope for this feature, I did this temporary fix so the app don't crash. 
- Updated the model and different db connections to support multilingual support
- Updated the route to add contents

The following changes have been made on the frontend
- Added functions to get a list of languages and the default language from the db. 
- Updated LanguageButtonBar to get content from the DB instead of the static dictionary.

I also made some major changes to the add content logic:
When accessing the edit page from the landing page (by clicking on new): We go to the edit page but with `content_id =null.`
Meaning that we will add a new Content and a new ContentText to the DB. After creating the new content, a model will show asking to created a new language version of the content or not.
- If yes, then we are redirected to the edit page but with the `content_id=created_content_id`.
- If not, then we are redirected to the landing page. 
That is one approach to creating many language version at the same time but I am open to implementing a better approach. 

One thing to have in mind is that I haven't updated the tests so they are failing for now. But will update them in the next couple of PRs
## How has this been tested?
Tried to add content several times, either one language at the time content at a time or several. I suggest to add a couple more languages using the endpoints to make sure the logic works.

## Checklist

Fill with `x` for completed. Delete any lines that are not relevant

- [x] My code follows the style guidelines of this project
- [x] I have reviewed my own code to ensure good quality
- [x] I have tested the functionality of my code to ensure it works as intended
- [x] I have resolved merge conflicts
- [ ] I have updated the automated tests (if applicable)
- [ ] I have updated the requirements (if applicable)
- [ ] I have updated the README file (if applicable)
- [ ] I have updated affected documentation (if applicable)

2024-03-22 16:20 UTC, lickem22 commented on admin_app/src/app/content/edit/page.tsx
> +  content_text_id: number | null;
This is not used yet  but will be used for the edit.

2024-03-22 16:21 UTC, lickem22 commented on admin_app/src/app/content/edit/page.tsx
> +  const [isSaved, setIsSaved] = React.useState(false);
I updated it to false to send a message whenever a content is succesfully updated to DB

2024-03-22 16:22 UTC, lickem22 commented on admin_app/src/app/content/edit/page.tsx
> +        <Dialog open={showModal} onClose={() => setShowModal(false)}>
Added this modal to give the option to add a new language version of a content instead of being redirect to the landing page automatically.

2024-03-25 16:44 UTC, sidravi1 requested changes
Thanks @lickem22!

Lots of good work here. But I'm really struggling with making sense of this. I can't tell what is meant to work and what is not. For example, if I add a new and then add a new language, it seems to be missing the old language? I can't see it on the main page so it's hard to know what was created.

Can i suggest you do it in this order:
 (a) list - create data in the backend and just show it on the main page
 (b) read - clicking on the "READ" button brings up a Dialog that should show all the content
 (c) edit - create data in the backend and just allow users to edit an existing content
 (d) edit + add new language - allow users to add a new language
 (e) add - allow users to add a new content

2024-03-25 16:44 UTC, sidravi1 commented on admin_app/src/components/LanguageButtonBar.tsx
> +        const languages = await apiCalls.getLanguageList(token ?? '');
Also, we shouldn't call api from low level components. Creates too much coupling and makes it hard to change things. Can I suggest calling the api at the higher level and passing `languages` as an property to the component?

2024-03-25 16:44 UTC, sidravi1 commented on admin_app/src/components/LanguageButtonBar.tsx
> +        const defaultLanguage = await apiCalls.getDefaultLanguage(token ?? '');
Same here

2024-03-25 16:44 UTC, sidravi1 commented on admin_app/src/components/LanguageButtonBar.tsx
> +        const languages = await apiCalls.getLanguageList(token ?? '');
Or pass `fetchLanguages` and `fetchDefaultLanguage` as props.

2024-03-25 16:44 UTC, sidravi1 commented on admin_app/src/components/LanguageButtonBar.tsx
> +      fetchLanguages();
if you pass token as a parameter, then you don't need to do `token!` or `token ?? ''`

2024-03-25 16:44 UTC, sidravi1 commented on admin_app/src/components/LanguageButtonBar.tsx
> +  }, [token, expandable]);
Why do we add `expandable` to this? It is not a state variable right and never changes?

2024-03-25 16:44 UTC, sidravi1 commented on admin_app/src/app/content/edit/page.tsx
> +  const [showModal, setShowModal] = React.useState(false);
Let's be more specific on what the modal is for.

2024-03-25 16:44 UTC, sidravi1 commented on admin_app/src/app/content/edit/page.tsx
> +    const promise = apiCalls.addContent(body, token!)
You have removed edit all together for now?

2024-03-25 16:44 UTC, sidravi1 commented on admin_app/src/app/content/edit/page.tsx
> +        return {
Isn't this a type? Can we initialize from there? We will add another prop to the type one day and forget to update this.

2024-03-25 16:44 UTC, sidravi1 commented on admin_app/src/app/content/edit/page.tsx
> +          created_datetime_utc: "",
Why empty strings and not null?

2024-03-25 16:44 UTC, sidravi1 commented on admin_app/src/app/content/edit/page.tsx
> +          <DialogTitle>New content successfully added</DialogTitle>
Can you mention id and for what language?

2024-03-25 16:44 UTC, sidravi1 commented on admin_app/src/app/content/edit/page.tsx
> +              Would you like to add a new language version for this content?
Mention content id?

2024-03-25 16:44 UTC, sidravi1 commented on admin_app/src/app/content/edit/page.tsx
> +              router.push(`/content/?content_id=${content_id}&action=view`);
I don't think content page takes these parameters.

2024-03-25 16:44 UTC, sidravi1 commented on admin_app/src/app/content/edit/page.tsx
> +              router.push(`/content/edit?content_id=${targetContentId}&action=add`);
But edit doesn't work yet, right?

2024-04-10 08:00 UTC, closed without merging