UD admin app
IDinsight/aaq-core pull request #186
Opened 2024-05-01 04:27 UTC by sidravi1

Reviewer: @lickem22 
Estimate: 1hrs

---

## Description

### Goal

Adds page Admin app to manage UD rules

### Changes

- API calls
- New page / updated nav bar

### Future Tasks (optional)
- Add to playground
- Docs and blogpost

## How has this been tested?

Start backend and admin app and CRUD rules!
## Checklist

Fill with `x` for completed. Delete any lines that are not relevant

- [x] My code follows the style guidelines of this project
- [x] I have reviewed my own code to ensure good quality
- [x] I have tested the functionality of my code to ensure it works as intended
- [x] I have resolved merge conflicts
- [x] I have updated the automated tests (if applicable)
- [x] I have updated the requirements (if applicable)
- [ ] I have updated the README file (if applicable)
- [ ] I have updated affected documentation (if applicable)

2024-05-02 10:00 UTC, lickem22 commented on admin_app/src/app/urgency-rules/page.tsx
> +  ListItemButton,
```suggestion
```

2024-05-02 10:00 UTC, lickem22 commented on admin_app/src/app/urgency-rules/page.tsx
> +  ListItemButton,
It was never used

2024-05-02 10:01 UTC, lickem22 commented on admin_app/src/app/urgency-rules/page.tsx
> +import CommentIcon from "@mui/icons-material/Comment";
```suggestion
```

2024-05-02 10:46 UTC, lickem22 commented on admin_app/src/app/urgency-rules/page.tsx
> +            const labelId = `checkbox-list-label-${index}`;
What is this for? It is not used anywhere. We should remove it if not useful.

2024-05-02 14:17 UTC, lickem22 requested changes
Thanks @sidravi1 . It is a strong first version. However I have a few comments:
- We should have a add button just like an edit and delete button. Because I am not sure it would be intuitive for users to only add by pressing enter. But it is still a good functionality to have. Ideally we would have both.
- There are a few bugs:
  - When you press enter without adding any urgent value, you get an empty field like this:
  
<img width="721" alt="Screenshot 2024-05-02 at 15 07 27" src="https://github.com/IDinsight/aaq-core/assets/44327443/a1042f81-c993-424c-86d2-d7b0846cce68">
And you cannot delete it afterwards. The delete button won't work. 

  - The same way when you click on delete on a row that has not been saved, you get the same result. I think we should make sure the delete button deletes the row even if it is not saved. 
  - We should also hide the edit button when a field has not been saved to the DB and when we are in edit mode. 

I know it was on short notice. But it would have been nice to have a design first for everyone to approve. That would have made the review easier. Thanks.

2024-05-02 18:26 UTC, sidravi1 commented on admin_app/src/app/urgency-rules/page.tsx
> +  const { token, accessLevel } = useAuth();
Ah! This reminds me to add access control. Added!

2024-05-02 19:36 UTC, sidravi1 commented
Thanks @lickem22! Sorry i missed that bug (really need some test cases!) and thank you for picking it up.
I have also added the send button as requested.

Yeah - i wanted to get this in quickly. We may be able to use google people to do the designs for this page.

2024-05-03 08:30 UTC, lickem22 commented on docs/components/index.md
Hi @sidravi1  I think there was an issue with the commits because the same changes are made here and in the [UD documentation PR](https://github.com/IDinsight/aaq-core/pull/191). Was it intentional?

2024-05-03 08:32 UTC, lickem22 commented on docs/components/urgency-detection/index.md
Same here

2024-05-03 08:37 UTC, lickem22 approved these changes
Thanks for making the changes @sidravi1. 
Only a few comments:
- The `new` button keeps adding new row even when nothing is saved. Could you disable the button until the row is either created or deleted ? Sorry I didn't notice that before 
- Also thanks for adding the access level. Currently there is a bug when using `readonly_user`:  the `new` button is disabled, but you can still double click to edit a row, use enter to edit and click on delete or edit. Which throws an error because of wrong credentials. The `send` button should also be disabled. Can you please fix that.
These are pretty minor fixes, so I approved the PR. 
Thanks a lot.

2024-05-03 16:25 UTC, sidravi1 commented
Thanks @lickem22 ! 
Both of these are good suggestions - thanks for picking them up. I have fixed both of these now.

2024-05-03 16:26 UTC, merged