Chat window - first draft
IDinsight/aaq-core pull request #48
Opened 2023-11-30 21:42 UTC by sidravi1

Reviewer: @ziakhan04 

Estimate: 1 hour

----

# Framework for a chat window

## Ticket

Fixes: [AAQ-190](https://idinsight.atlassian.net/browse/AAQ-190?atlOrigin=eyJpIjoiNWQyMmMwNzQ3ZTExNDM4MWJmZmMyZWZmYWNmODQyOTgiLCJwIjoiaiJ9)

## Description, Motivation and Context

We want to allow admins to be able to test out reponses for messages

### Changes

Added a new page.
Updated nav bar.
Some minor cosmetic changes.

## Next steps

* Make prettier
* Allow toggling - raw response, top n answers, llm response
* Fix hacky solution for getting backend token

## How Has This Been Tested?

Clicked around (though we do need to get better at this)

## Checklist:

This checklist is a useful reminder of small things that can easily be forgotten.
Put an `x` in all the items that apply and remove any items that are not relevant to this PR.

- [x] My code follows the style guidelines of this project
- [x] I have reviewed my own code to ensure good quality
- [x] I have tested the functionality of my code to ensure it works as intended
- [x] I have resolved merge conflicts
- [ ] I have updated the automated tests (if applicable)
- [x] I have written [good commit messages][1]
- [ ] I have updated the README file (if applicable)
- [ ] I have updated affected documentation (if applicable)

[1]: http://chris.beams.io/posts/git-commit/

2023-11-30 21:44 UTC, sidravi1 commented on admin_app/src/app/layout.tsx
> +import { NavBar } from "../components/NavBar";
Now it's added to all pages automatically

2023-11-30 21:44 UTC, sidravi1 commented on admin_app/src/app/page.tsx
> +import { backendUrl } from "../components/Config";
new file for all the config so we are not repeating this line everywhere

2023-11-30 21:44 UTC, sidravi1 commented on admin_app/src/components/ChatComponents.tsx
> +    let token: string | null = localStorage.getItem("apiToken");
This is a very hacky solution. Something I'll fix in the next PR

2023-12-01 11:49 UTC, ziakhan04 requested changes
Looks good and works!

One question - Should both fullaccess and readonly get access to chat (happening right now)?

Added minor comments.

Suggested changes -
- The background colour doesn't match across content and playground pages
- Navbar does not correctly show which page I am on. Always defaults to highlighting "Home".

Other stuff that I made tickets out of (not necessarily related to this ticket) -
- Hydration error occurs when I login and log-out. Don't know what it is. (screenshot)
- When the screen is narrow, navbar becomes three line which are non-responsive. (screenshot)
- Pressing "Enter" in the chat to send message instead of manually clicking "Send".
- AI response has area for improvement visually. (No screenshot, don't want the developer to get a heart-attack)

2023-12-01 18:20 UTC, sidravi1 commented on admin_app/src/components/ChatComponents.tsx
> +    let token: string | null = localStorage.getItem("apiToken");
Yeah! Problems are: 
* there is no way to edit your token once you have entered it
* so if you enter is wrong, you may have to restart your browser 🙈 

There is the cosmetic aspect of it but also the functional. I'll fix it in the next PR.

2023-12-01 18:28 UTC, sidravi1 commented on admin_app/src/components/NavBar.tsx
> +                href="/chat"
Yeah there is another ticket called "make nav bar functional" or something similar. I threw the navbar together as a placeholder and not fully functional.

2023-12-01 18:41 UTC, sidravi1 commented on admin_app/src/app/chat/page.tsx
> +      <main className="flex flex-grow justify-center h-full dark:bg-gray-900 py-4 border-neutral-800 rounded-md">
Thanks for picking this up. Fixed so they both inherit background from body in both dark and light mode.

2023-12-01 18:43 UTC, sidravi1 commented on admin_app/src/components/ChatComponents.tsx
> +        className="bg-gray-200 dark:bg-gray-800 p-2 flex-1 rounded-md border border-red-200"
No you're right. Made it something more neutral

2023-12-04 17:00 UTC, merged